name: Calibre

on:
  push:
    paths:
      - calibre/Dockerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./calibre/Dockerfile
