name: Calibre

on:
  push:
    tags:
      - '*'
    paths:
      - './Dockerfile'

  workflow_dispatch:

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t calibre:local -f ./Dockerfile .
      - name: Run Trivy Vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          ignore-unfixed: true
          image-ref: 'calibre:local'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
  build:
    needs: [security-check]
    runs-on: ubuntu-latest
    environment:
      name: calibre
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set application version based on the tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          build-args: CALIBRE_RELEASE=${{ steps.vars.outputs.tag }}
          push: true
          tags: |
            lucapisciotta/calibre:latest
            lucapisciotta/calibre:${{ steps.vars.outputs.tag }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: lucapisciotta/calibre
          readme-filepath: ./README.md